"""Generate the 18 main-grid configs + 2 optional ablation configs, plus
configs/_index.json, from the assignments fixed in EXPERIMENT_PLAN.md.

Idempotent: rerunning regenerates the same files byte-for-byte.

CLI:
  python scripts/gen_configs.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIGS_DIR = ROOT / "configs"

DEFAULTS = {
    "model": "resnet18",
    "epochs": 200,
    "batch_size": 128,
    "lr": 0.1,
    "momentum": 0.9,
    "weight_decay": 0.0005,
    "augmentation": "standard",
    "use_amp": True,
    "amp_dtype": "bfloat16",
    "num_workers": 4,
    "lr_schedule": "cosine",
    "sharpness_batch_size": 512,
}

SWA_DEFAULTS = {
    "swa_start_epoch": 160,   # Izmailov budget-1 protocol: start at 75% of epochs (rounded)
    "swa_lr": 0.005,          # ~ lr/20; conservative low-LR averaging window
}

# Per-cell wall-clock (hours) on RTX 3070 with AMP bf16 + num_workers=4,
# derived from spike + smoke timings (200 epochs + eval):
#   SGD/SWA CIFAR-10:  0.87 h
#   SGD/SWA CIFAR-100: 0.91 h
#   SAM CIFAR-10:      1.67 h
#   SAM CIFAR-100:     1.75 h
PACE = {
    "khanh_3070": 1.0,
    "friend_3060": 1.0 / 0.85,   # ~1.176x baseline wall-clock
    "khanh_colab": 2.0,          # T4-equivalent
    "friend_colab": 2.0,         # T4-equivalent
}


def base_hours(opt, dataset):
    if opt == "sam":
        return 1.67 if dataset == "cifar10" else 1.75
    return 0.87 if dataset == "cifar10" else 0.91


# Runner assignments from EXPERIMENT_PLAN.md §11.3
ASSIGNMENTS = [
    # khanh_3070 (4 configs; SAM cells)
    ("sam", "cifar100", 1, 0.05, "khanh_3070"),
    ("sam", "cifar100", 2, 0.05, "khanh_3070"),
    ("sam", "cifar100", 3, 0.05, "khanh_3070"),
    ("sam", "cifar10",  1, 0.05, "khanh_3070"),
    # friend_3060 (5 configs)
    ("sam", "cifar10",  2, 0.05, "friend_3060"),
    ("sam", "cifar10",  3, 0.05, "friend_3060"),
    ("sgd", "cifar100", 1, None, "friend_3060"),
    ("swa", "cifar100", 1, None, "friend_3060"),
    ("swa", "cifar10",  1, None, "friend_3060"),
    # khanh_colab (5 configs)
    ("sgd", "cifar100", 2, None, "khanh_colab"),
    ("sgd", "cifar10",  1, None, "khanh_colab"),
    ("sgd", "cifar10",  2, None, "khanh_colab"),
    ("sgd", "cifar10",  3, None, "khanh_colab"),
    ("swa", "cifar10",  2, None, "khanh_colab"),
    # friend_colab (4 configs)
    ("swa", "cifar100", 2, None, "friend_colab"),
    ("swa", "cifar100", 3, None, "friend_colab"),
    ("sgd", "cifar100", 3, None, "friend_colab"),
    ("swa", "cifar10",  3, None, "friend_colab"),
]

# Optional ablations: rho ∈ {0.02, 0.10} on CIFAR-100 seed 1.
# Assigned to khanh_3070 after main grid completes.
ABLATIONS = [
    ("sam", "cifar100", 1, 0.02, "khanh_3070"),
    ("sam", "cifar100", 1, 0.10, "khanh_3070"),
]


def run_id(opt, dataset, seed, rho):
    if opt == "sam":
        rho_int = int(round(rho * 100))  # 0.05 -> 5, 0.02 -> 2, 0.10 -> 10
        return f"sam{rho_int:03d}_{dataset}_s{seed}"
    return f"{opt}_{dataset}_s{seed}"


def render_yaml(opt, dataset, seed, rho, runner, optional):
    rid = run_id(opt, dataset, seed, rho)
    L = [
        "# Auto-generated by scripts/gen_configs.py — do not hand-edit.",
        f"# Production config (stage E). assigned_runner: {runner}",
    ]
    if optional:
        L.append("# OPTIONAL ablation — run only after main grid completes.")
    L += [
        "",
        f"run_id: {rid}",
        f"optimizer: {opt}",
    ]
    if opt == "sam":
        L.append(f"rho: {rho}")
    if opt == "swa":
        for k, v in SWA_DEFAULTS.items():
            L.append(f"{k}: {v}")
    L.append(f"dataset: {dataset}")
    L.append(f"seed: {seed}")
    L.append("")
    L.append("# Training settings (shared across all production configs)")
    for k, v in DEFAULTS.items():
        if isinstance(v, bool):
            L.append(f"{k}: {str(v).lower()}")
        else:
            L.append(f"{k}: {v}")
    L.append("")
    L.append(f"assigned_runner: {runner}")
    if optional:
        L.append("optional: true")
    return "\n".join(L) + "\n"


def main():
    CONFIGS_DIR.mkdir(parents=True, exist_ok=True)

    entries = []
    by_runner = {}
    for *spec, runner in ASSIGNMENTS:
        by_runner.setdefault(runner, []).append((tuple(spec) + (runner,), False))
    for *spec, runner in ABLATIONS:
        by_runner.setdefault(runner, []).append((tuple(spec) + (runner,), True))

    for runner, items in by_runner.items():
        # Within each runner: longest first (descending hours), with optional pushed to the end.
        def sort_key(item):
            (opt, ds, seed, rho, _), optional = item
            hours = base_hours(opt, ds) * PACE[runner]
            return (optional, -hours, opt, ds, seed)

        items.sort(key=sort_key)
        for priority, ((opt, ds, seed, rho, _), optional) in enumerate(items, start=1):
            rid = run_id(opt, ds, seed, rho)
            (CONFIGS_DIR / f"{rid}.yaml").write_text(
                render_yaml(opt, ds, seed, rho, runner, optional)
            )
            hours = base_hours(opt, ds) * PACE[runner]
            entries.append({
                "run_id": rid,
                "config_path": f"configs/{rid}.yaml",
                "assigned_runner": runner,
                "optimizer": opt,
                "dataset": ds,
                "seed": seed,
                "rho": rho,
                "estimated_wall_clock_h_on_runner": round(hours, 2),
                "priority_within_runner": priority,
                "optional": optional,
                "status": "pending",
            })

    entries.sort(key=lambda e: (e["assigned_runner"], e["priority_within_runner"]))

    queue_totals = {}
    for e in entries:
        if e["optional"]:
            continue
        queue_totals.setdefault(e["assigned_runner"], 0.0)
        queue_totals[e["assigned_runner"]] += e["estimated_wall_clock_h_on_runner"]
    queue_totals = {k: round(v, 2) for k, v in queue_totals.items()}

    index = {
        "generated_by": "scripts/gen_configs.py",
        "n_configs_total": len(entries),
        "n_main": sum(1 for e in entries if not e["optional"]),
        "n_optional": sum(1 for e in entries if e["optional"]),
        "queue_totals_h_main_grid": queue_totals,
        "longest_runner_wall_clock_h": max(queue_totals.values()) if queue_totals else 0,
        "primary_metrics_required": ["ood_accuracy_avg", "paired_cka_penultimate", "sharpness_top_eig"],
        "configs": entries,
    }
    (CONFIGS_DIR / "_index.json").write_text(json.dumps(index, indent=2))

    print(f"Wrote {len(entries)} config(s) to {CONFIGS_DIR}/")
    print(f"  main: {index['n_main']}, optional: {index['n_optional']}")
    for runner, hours in sorted(queue_totals.items()):
        print(f"  {runner:13s}: {hours:.2f} h projected queue time (main only)")
    print(f"  Longest runner queue: {index['longest_runner_wall_clock_h']:.2f} h")


if __name__ == "__main__":
    main()
